name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - target: x86_64-apple-darwin
            runs-on: macos-latest
          # TODO Add aarch64-darwin build
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Test
        run: cargo test
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: |
            --release
            --target ${{ matrix.target }}
      - name: Package
        uses: a7ul/tar-action@v1.1.0
        with:
          cwd: target/${{ matrix.target }}/release/
          files: |
            edssh
          command: c
          outPath: edssh-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          files: edssh-${{ github.ref_name }}-${{ matrix.target }}.tar.gz